---
# Build Configuration for Cleanuparr Add-on
# This file configures the build process for the Home Assistant add-on

# Base Images per Architecture
# Using Home Assistant's minimal base images (Alpine Linux 3.20)
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
# Build Arguments
# These are passed to the Dockerfile during build
args:
  CLEANUPARR_VERSION: "2.5.1"
  BUILD_DATE: "2024-01-27"
# Docker Labels
# Metadata for the container image
labels:
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: cleanuparr"
  org.opencontainers.image.description: "Automated cleanup for Sonarr, Radarr, Lidarr, Readarr, and Whisparr downloads"
  org.opencontainers.image.source: "https://github.com/rigerc/home-assistant-addons/cleanuparr"
  org.opencontainers.image.licenses: "Apache License 2.0"
  org.opencontainers.image.authors: "Your Name <you@example.com>"
  org.opencontainers.image.created: "2026-01-28T00:01:44Z"
  org.opencontainers.image.version: "0.2.0"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/cleanuparr/README.md
  org.opencontainers.image.revision: 2e7b23442026f8961d40672ad195d1ed75dff976
# Codenotary Configuration
# Optional: Sign your images for verification (+1 security point)
# codenotary:
#   signer: "developer@example.com"
#   base_image: "notary@home-assistant.io"
