build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Simple Wrapper"
  org.opencontainers.image.description: "Example wrapper add-on"
  io.hass.upstream.image: "alpine"
