---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: romm"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.source: https://github.com/rigerc/home-assistant-addons/romm
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/romm/README.md
  org.opencontainers.image.created: "2026-01-26T02:11:26Z"
  org.opencontainers.image.revision: 600fc47e967537ea23d3fae6326af8e92acfd9ed
  org.opencontainers.image.version: 0.1.14
