build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"

args:
  ROMM_VERSION: "3.5.1"

labels:
  org.opencontainers.image.title: "Romm - ROM Manager"
  org.opencontainers.image.description: "Beautiful, powerful, self-hosted ROM manager for retro gaming"
  org.opencontainers.image.source: "https://github.com/rommapp/romm"
  org.opencontainers.image.licenses: "AGPL-3.0"
